# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:alpine3.20
    restart: always
    ports:
      - 5432:5432
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - /Users/thepphithakp/code-work-spaces/scb/docker-as-a-service/pgsql-server/data:/var/lib/postgresql/data
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: postgres

volumes:
  db-data:
    driver: local
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080